# Generated by Django 4.1.4 on 2023-01-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlFacture',
            fields=[
                ('code_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('totalht', models.FloatField(default=0)),
                ('totalttc_bl', models.FloatField(default=0)),
                ('totalttc_fac', models.FloatField(default=0)),
                ('date_doc', models.DateTimeField()),
                ('remise', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BondeCommande',
            fields=[
                ('code_bc', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_cat', models.AutoField(primary_key=True, serialize=False)),
                ('designation_cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_cl', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cl', models.CharField(max_length=254)),
                ('prenom_cl', models.CharField(max_length=255)),
                ('adr_cl', models.CharField(max_length=255)),
                ('tel_cl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_favorite', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaiementCredit',
            fields=[
                ('code_pc', models.AutoField(primary_key=True, serialize=False)),
                ('etat_pc', models.BooleanField(default=True)),
                ('montant_credit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=255)),
                ('type_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('code_reg', models.AutoField(primary_key=True, serialize=False)),
                ('etat_reg', models.BooleanField(default=False)),
                ('montant_payé', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code_etat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_stock', models.CharField(max_length=254)),
                ('benefice', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenteAuComptoire',
            fields=[
                ('code_vente', models.AutoField(primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
                ('stock', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='VenteAuComptoireProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_prod', models.FloatField()),
                ('prixU_vente', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
                ('vente_au_comptoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venteaucomptoire')),
            ],
        ),
        migrations.CreateModel(
            name='StockProduit',
            fields=[
                ('primary_key', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('qteDispo', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_fr', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fr', models.CharField(max_length=254)),
                ('prenom_fr', models.CharField(max_length=255)),
                ('adr_fr', models.CharField(max_length=255)),
                ('tel_fr', models.CharField(max_length=255)),
                ('reglement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reglement')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='paiement_credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.paiementcredit'),
        ),
        migrations.CreateModel(
            name='BondeCommandeProduit',
            fields=[
                ('primary_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('qteProdBC', models.PositiveIntegerField()),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bondecommande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur'),
        ),
        migrations.CreateModel(
            name='BlFactureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteprodbl', models.IntegerField()),
                ('prix_ht', models.FloatField()),
                ('prix_vente_fr', models.FloatField()),
                ('bl_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blfacture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.AddField(
            model_name='blfacture',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur'),
        ),
        migrations.AddField(
            model_name='blfacture',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stock'),
        ),
    ]
