# Generated by Django 4.1.4 on 2023-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_venteaucomptoire_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteaucomptoire',
            name='total_vente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='venteaucomptoire',
            name='date_vente',
            field=models.DateTimeField(),
        ),
    ]
