# Generated by Django 4.1.3 on 2023-01-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_venteaucomptoire_total_vente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiementcredit',
            old_name='montant_credit',
            new_name='montant_payé',
        ),
    ]
