# Generated by Django 4.1.5 on 2023-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_montant_credit_paiementcredit_montant_payé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteaucomptoireproduit',
            name='qte_prod',
            field=models.IntegerField(),
        ),
    ]
